import Link from "next/link";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="bg-blue-100 dark:bg-blue-800 text-black dark:text-white p-1 m-2 rounded-md">
      <div className="container mx-auto">
        <nav className="flex items-center justify-between">
          <div className="flex items-center">
            <Link href="/">Home</Link>
          </div>
          <div className="flex items-center">
            <Link href="/mountain">Mountain</Link>
          </div>
          <div className="flex items-center">
            <Link href="/contact">Contact</Link>
          </div>
          <div className="flex items-center">
            <Link href="/hotels">Hotels</Link>
          </div>
          <div className="flex items-center">
            <Link href="/tailwind">Tailwind</Link>
          </div>
        </nav>
      </div>
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
